### ISSUE TITLE
error on gulp default

### ISSUE THREAD

**Issue by dendybsulistyo** [HarrisJT/web-launch-checklist#3]
after npm install, i do sudo gulp default, but it shows the errors,

sudo gulp default
[11:10:59] Using gulpfile /Applications/MAMP/htdocs/ceklist/gulpfile.js
[11:10:59] Starting 'default'...
[11:10:59] Starting 'js'...
[11:11:00] Finished 'js' after 576 ms
[11:11:00] Starting 'css'...
[11:11:00] 'css' errored after 224 ms
[11:11:00] TypeError in plugin 'gulp-autoprefixer'
Message:
    this is not a typed array.
Details:
    fileName: /Applications/MAMP/htdocs/ceklist/_include/css/main.css
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
Stack:
TypeError: this is not a typed array.
    at Function.from (native)
    at /Applications/MAMP/htdocs/ceklist/node_modules/gulp-autoprefixer/index.js:25:27
    at process._tickDomainCallback (node.js:411:9)
[11:11:00] 'default' errored after 805 ms

**Comment by HarrisJT** [comment]
Have you tried updating your node? I will look into this
